os: osx
language: node_js
node_js:
  - "stable"
before_install:
  - brew update
  - brew install hugo
install:
  - npm install
script:
  - git config --global merge.renameLimit 999999
  - ls
  - hugo
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master